spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://welcomeydb.cf7a7qhcvsyv.us-east-2.rds.amazonaws.com/welcomeydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: yyyy302gh

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    #      show_sql: true
    #      format_sql: true

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    com.jpa.student: debug
    #org.hibernate.SQL: debug
    #org.hibernate.type: trace

server:
  port: 8080
  servlet:
    encoding:
      force-response: true

naver-cloud-sms:
  accessKey: "EV53EtrDkCGR8bHufLr6"
  secretKey: "qu2XhcFfeOzRyapuvtF5VP4HDHrTXpPtJwivC6I3"
  serviceId: "ncp:sms:kr:305699022048:reserveproject"
  senderPhone: "010-4134-2824"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true